coverage:
  status:
    patch:
      default:
        target: 60%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target
    project:
      default:
        target: 60%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target
